<a href="https://colab.research.google.com/github/SiracencoSerghei/Bootcamp_Python/blob/master/day_72/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving salaries_by_college_major.csv to salaries_by_college_major (2).csv

---
# Goals
---

**Learn Data Exploration with Pandas by Analysing the Post-University Salaries of Graduates by Major**


College degrees are very expensive. But, do they pay you back? Choosing
Philosophy or International Relations as a major may have worried your parents, but does the data back up their fears? PayScale Inc. did a year-long survey of 1.2 million Americans with only a bachelor's degree. We'll be digging into this data and use Pandas to answer these questions:



Which degrees have the highest starting salaries?

Which majors have the lowest earnings after college?

Which degrees have the highest earning potential?

What are the lowest risk college majors from an earnings standpoint?

Do business, STEM (Science, Technology, Engineering, Mathematics) or HASS (Humanities, Arts, Social Science) degrees earn more on average?



---

Today you'll learn

How to explore a Pandas DataFrame

How to detect NaN (not a number) values and clean your data

How to select particular columns, rows, and individual cells

How to sort your data

How to group data by category

---
# Points
---

Points



Use .head(), .tail(), .shape and .columns to explore your DataFrame and find out the number of rows and columns as well as the column names.

Look for NaN (not a number) values with .findna() and consider using .dropna() to clean up your DataFrame.

You can access entire columns of a DataFrame using the square bracket notation: df['column name'] or df[['column name 1', 'column name 2', 'column name 3']]

You can access individual cells in a DataFrame by chaining square brackets df['column name'][index] or using df['column name'].loc[index]

The largest and smallest values, as well as their positions, can be found with methods like .max(), .min(), .idxmax() and .idxmin()

You can sort the DataFrame with .sort_values() and add new columns with .insert()

To create an Excel Style Pivot Table by grouping entries that belong to a particular category use the .groupby() method

---
# Upload the **Data** and **Read** *the .csv* File
---

In [53]:
df = pd.read_csv('salaries_by_college_major.csv')
df.head(3)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business

---
# Preliminary Data **Exploration** and Data **Cleaning** with Pandas
---

In [54]:
df.shape

(51, 6)

In [4]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [5]:
df.isna().sum()

Undergraduate Major                  0
Starting Median Salary               1
Mid-Career Median Salary             1
Mid-Career 10th Percentile Salary    1
Mid-Career 90th Percentile Salary    1
Group                                1
dtype: int64

In [6]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [7]:
clean_df = df.dropna()
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

---
# **Accessing Columns and Individual Cells** in a Dataframe
---

In [8]:
clean_df['Starting Median Salary'].head(3)

0    46000.0
1    57700.0
2    42600.0
Name: Starting Median Salary, dtype: float64

In [9]:
clean_df['Starting Median Salary'].max()

74300.0

In [10]:
clean_df['Starting Median Salary'].idxmax()

43

In [11]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [30]:
clean_df.loc[1]

Undergraduate Major                  Aerospace Engineering
Spread                                             96700.0
Starting Median Salary                             57700.0
Mid-Career Median Salary                          101000.0
Mid-Career 10th Percentile Salary                  64300.0
Mid-Career 90th Percentile Salary                 161000.0
Group                                                 STEM
Name: 1, dtype: object

In [13]:
## The Highest Mid-Career Salary

In [14]:
print(clean_df['Mid-Career Median Salary'].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][8]

107000.0
Index for the max mid career salary: 8

'Chemical Engineering'

In [15]:
## The Lowest Starting and Mid-Career Salary

In [16]:
print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

In [17]:

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

---
# **Sorting Values & Adding Columns**: Majors with the Most Potential vs Lowest Risk
---

In [29]:
## Lowest Risk Majors
(clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']).loc[1]

96700.0

In [27]:
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary']).loc[1]

96700.0

In [21]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [22]:
## Sorting by the Lowest Spread

In [37]:
# low_risk = clean_df.sort_values('Spread')
low_risk = clean_df.sort_values('Spread', ascending=False)
low_risk[['Undergraduate Major', 'Spread']].head(7)

     Undergraduate Major    Spread
17             Economics  159400.0
22               Finance  147800.0
37                  Math  137800.0
36             Marketing  132900.0
42            Philosophy  132500.0
45     Political Science  126800.0
8   Chemical Engineering  122100.0

In [47]:
highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major','Mid-Career 90th Percentile Salary']].head(5)

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [50]:
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [51]:
highest_spread_medium = clean_df.sort_values('Mid-Career Median Salary', ascending=False)
highest_spread_medium[['Undergraduate Major', 'Mid-Career Median Salary']].head()

       Undergraduate Major  Mid-Career Median Salary
8     Chemical Engineering                  107000.0
12    Computer Engineering                  105000.0
19  Electrical Engineering                  103000.0
1    Aerospace Engineering                  101000.0
17               Economics                   98600.0

---
# **Grouping** and **Pivoting** Data with Pandas
---

In [55]:
grouped = clean_df.groupby('Group').count()
grouped

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [61]:
# clean_df.groupby('Group').mean()  # TypeError: agg function failed [how->mean,dtype->object]
# The mean() function cannot work with columns that contain text (non-numeric) data.

clean_df.groupby('Group').mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,103958.333333,44633.333333,75083.333333,43566.666667,147525.000000
HASS,95218.181818,37186.363636,62968.181818,34145.454545,129363.636364
STEM,101600.000000,53862.500000,90812.500000,56025.000000,157625.000000

In [62]:
# Number formats in the Output

pd.options.display.float_format = '{:,.2f}'.format

clean_df.groupby('Group').mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"